version: '3.8'

services:

    #PHP
    php:
        build: images/php
        image: php:7-alpine
        container_name: php
        restart: unless-stopped
        volumes:
            - ../app:/app
        user: 1000:1000
        ports:
            - 8080:8080
            - 8888:8888
        depends_on:
            - mysql
        command: sh -c 'composer install -d /app/api/ && php -S 0.0.0.0:8080 -t /app/api/public & php -S 0.0.0.0:8888 -t /app/view/build'
        
    # MYSQL
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./applications/mysql/data:/var/lib/mysql
            - ./applications/mysql/conf.d:/etc/mysql/conf.d
        ports:
            - 3306:3306
        env_file:
            - ./env/mysql/global.env